In [3]:
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'
import numpy as np
pd.set_option('display.max_rows', 1000)
knot_info = pd.read_csv('Knotinfo_data.csv', dtype='object')  

import sklearn
import scipy
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn import preprocessing
from sklearn.preprocessing import PolynomialFeatures
from sklearn.feature_selection import VarianceThreshold
import itertools


# import required module for iterating through directory
import os
import json
# assign directory
directory = 'data'
#we create a dictionary with keys: names of knots
                          #values: dictionaries (keys: nonzero gradings, values: homology dimensions)
homfly_data={}
# sort directory and then iterate over files in that directory, creating a dictionary for easier use
listing = os.listdir(directory)
listing.sort()
for filename in listing:
    f = os.path.join(directory, filename)
    # checking if it is a file
    if os.path.isfile(f):
        with open(f) as json_file:
            data = json.load(json_file)
            data_dict = {}
            for i in range(int(len(data)/2)):
                data_dict[tuple(data[2*i])]=data[2*i+1]
            homfly_data[filename[:-5]]=data_dict

In [48]:
#X is m x n, 
#y is m x 1, 
#theta is n x 1
def L_infty_cost(X,y,theta):
    errors = np.abs(np.matmul(CKI,theta)-y)
    return np.amax(errors)

In [8]:
all_knot_info = pd.read_csv('all_knotinfo.csv') 
all_knot_info.shape[1]

78

In [19]:
all_knot_info

,Name,Alternating,Two-Bridge Notation,Fibered,Crossing Number,Unknotting Number,Genus-3D,Crosscap Number,Bridge Index,Braid Index,...,L-space,Nu,Epsilon,Quasialternating,Almost Alternating,Adequate,Montesinos Notation,Boundary Slopes,Pretzel Notation,Double Slice Genus
0,3_1,Y,3/1,Y,3,1,1,1,2,2,...,Yes,{1;-1},1,Y,N,Y,K(1/3),{0;6},P(-1;-1;-1),2
1,4_1,Y,5/2,Y,4,1,1,2,2,3,...,No,{0;0},0,Y,N,Y,K(2/5),{-4;0;4},P(1;1;2),2
2,5_1,Y,5/1,Y,5,2,2,1,2,2,...,Yes,{2;-2},1,Y,N,Y,K(1/5),{0;10},P(-1;-1;-1;-1;-1),4
3,5_2,Y,7/3,N,5,1,1,2,2,3,...,No,{1;-1},1,Y,N,Y,K(3/7),{0;4;10},P(-1;-1;-3),2
4,6_1,Y,9/7,N,6,1,1,2,2,4,...,No,{0;0},0,Y,N,Y,K(4/9),{-4;0;8},P(-1;-1;-4),1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2972,12n_884,N,NaN,N,12,1,2,4,3,5,...,No,{0;0},0,NaN,NaN,NaN,Not Montesinos,NaN,NaN,2
2973,12n_885,N,NaN,N,12,[1;2],3,[2;5],3,5,...,No,{0;0},0,NaN,NaN,NaN,Not Montesinos,NaN,NaN,2
2974,12n_886,N,NaN,N,12,2,3,[2;5],3,5,...,No,{1;0},1,NaN,NaN,NaN,Not Montesinos,NaN,NaN,2
2975,12n_887,N,NaN,Y,12,2,4,[2;5],3,3,...,No,{2;-1},1,NaN,NaN,NaN,Not Montesinos,NaN,NaN,4
2976,12n_888,N,NaN,Y,12,5,5,[2;4],3,3,...,No,{5;-4},1,NaN,NaN,NaN,Not Montesinos,NaN,NaN,10

In [16]:
data=[[1.0]]*78

In [17]:
df = pd.DataFrame(data)

In [18]:
all_knot_info*df

,0,A-Polynomial,Adequate,Alexander,Almost Alternating,Alternating,Arc Index,Arf Invariant,Boundary Slopes,Braid Index,...,Super Bridge Index,Symmetry Type,Thurston-Bennequin Number,Torsion Numbers,Tunnel Number,Turaev Genus,Two-Bridge Notation,Unknotting Number,Volume,Width
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2973,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
cleaned_knot_info = pd.read_csv('cleaned_knot_info.csv')  
cleaned_knot_info.dtypes

Alternating             float64
Fibered                 float64
Crossing Number         float64
Unknotting Number       float64
Genus-3D                float64
Crosscap Number         float64
Bridge Index            float64
Braid Index             float64
Braid Length            float64
Signature               float64
Nakanishi Index         float64
Arc Index               float64
Tunnel Number           float64
Morse-Novikov Number    float64
Genus-4D                float64
Genus-4D (Top.)         float64
Concordance Genus       float64
Determinant             float64
Rasmussen s             float64
Ozsvath-Szabo tau       float64
Volume                  float64
Arf Invariant           float64
Turaev Genus            float64
Small or Large          float64
Positive Braid          float64
Positive                float64
SQ-Positive             float64
Q-Positive              float64
Width                   float64
L-space                 float64
Epsilon                 float64
Quasialternating        float64
Almost Alternating      float64
Double Slice Genus      float64
dtype: object

In [27]:
CKI = cleaned_knot_info.to_numpy()

In [30]:
CKI.shape

(413, 34)

In [32]:
theta = np.array([1]*CKI.shape[1])
theta.shape

(34,)

In [43]:
y = np.array([1]*CKI.shape[0])

In [36]:
(CKI*theta).shape

(413, 34)

In [34]:
CKI

array([[ 1.,  1.,  3., ...,  1.,  0.,  2.],
       [ 1.,  1.,  4., ...,  1.,  0.,  2.],
       [ 1.,  1.,  5., ...,  1.,  0.,  4.],
       ...,
       [ 1.,  0., 11., ...,  1.,  0.,  6.],
       [ 1.,  1., 11., ...,  1.,  0., 10.],
       [ 0.,  1., 11., ...,  0.,  1.,  4.]])

In [38]:
np.matmul(CKI,theta).shape

(413,)

In [40]:
np.array([[1],[1]])-np.array([[2],[3]])

array([[-1],
       [-2]])

In [49]:
L_infty_cost(CKI,y,theta)

313.22857001